###
GET http://localhost:3000/plant

###
GET http://localhost:3000/plant?location=Mannheim

###
POST http://localhost:3000/plant
Content-Type: application/json

{
    "id": "1005",
    "name": "Mannheim Factory",
    "location": "Mannheim"
}

###
GET http://localhost:3000/product

###
GET http://localhost:3000/product?name=iPhone 14

###
GET http://localhost:3000/product?plant=1001

###
GET http://localhost:3000/product?name=iPhone 14&plant=1002

###
POST http://localhost:3000/product
Content-Type: application/json

{
    "name": "iPhone 15 Pro Max",
    "plant": "1003",
    "price": 1600
}